#pragma once

#include "Basic/Practice1/Practice1.h"
#include "Basic/Practice2/Practice2.h"
#include "Basic/Practice3/Practice3.h"
#include "Basic/Practice4/Practice4.h"
#include "Basic/Practice5/Practice5.h"
#include "Basic/Practice6/Practice6.h"
#include "Basic/Practice7/Practice7.h"

#include "Lighting/Color/Color.h"
#include "Lighting/BasicLighting/BasicLighting.h"
#include "Lighting/MaterialPractice/MaterialPractice.h"
#include "Lighting/LightingMap/LightingMap.h"
#include "Lighting/DirectionalLight/DirectionalLight.h"
#include "Lighting/PointLight/PointLight.h"
#include "Lighting/Spotlight/Spotlight.h"
#include "Lighting/MultipleLights/MultipleLights.h"

#include "Advanced_OpenGL/DepthTest/DepthTest.h"
#include "Advanced_OpenGL/StencilTest/StencilTest.h"
#include "Advanced_OpenGL/Blending/Blending.h"
#include "Advanced_OpenGL/Culling/Culling.h"
#include "Advanced_OpenGL/FrameBuffer/FrameBuffer.h"
#include "Advanced_OpenGL/SkyBox/SkyBox.h"
#include "Advanced_OpenGL/Build-inVar/Build_inVar.h"
#include "Advanced_OpenGL/TriangleHouse/TriangleHouse.h"
#include "Advanced_OpenGL/Instancing/Instancing.h"
